# Generated by Django 2.1.5 on 2019-01-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Categories'},
        ),
    ]
